### PR TITLE
Implement more circle related features

### PR DESCRIPTION
**Pull request by InusualZ**
This are all the changes that I have accumulated over time, about the circle functionality. I have tried to make every commit as atomic as possible, so you could review it commit by commit. 

I wanted to keep going and implement a few more thing, but I realized that we needed to change the `Players` collection object, and since it's not strictly related to circles I wanted to get this in first.

(If you need me to describe the PR a little bit more, ping me)

---
This change is [Reviewable](https://reviewable.io/reviews/sepalani/mh3sp/35)

### CODE REVIEW

**Review by sepalani — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sepalani/mh3sp/35)* status: all files reviewed, 6 unresolved discussions (waiting on @InusualZ)

___
*[-- commits, line 38 at r9](https://reviewable.io/reviews/sepalani/mh3sp/35#-MwkAcyu3yBHeY9nGvhE):*
`whether`
___
*[fmp_server.py, line 752 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7hdT9Nq6W_2mmrJ2:-Mwk7hdT9Nq6W_2mmrJ3:b5p7294) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L752)):*
> ```Python
>         """
> 
>         # Unknown field but it doesn't matter becase the client ignore it
> ```

`because` (...) `the client ignores it`
___
*[fmp_server.py, line 767 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7ttT5utvUxfinWIs:-Mwk7ttT5utvUxfinWIt:b-89a4l7) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L767)):*
> ```Python
>         """
> 
>         # Unknown field but it doesn't matter becase the client ignore them
> ```

Ditto
___
*[fmp_server.py, line 736 at r8](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk8jZo4U39NGqzKjAW:-Mwk8jZo4U39NGqzKjAX:b-fgic8c) ([raw file](https://github.com/sepalani/mh3sp/blob/8e5212f499533c0ae8c7319a588265246a822eaa/fmp_server.py#L736)):*
> ```Python
>         if circle.leader == self.session:
>             self.sendNtcCircleBreak(circle, seq)
>             circle.reset()
> ```

Can't this code-logic stay in the `leave_circle` method? Won't something like this work in the `leave_circle` method?
```python
if circle.leader == self:
    circle.reset()
```
___
*[mh/database.py, line 89 at r1](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk3i774vA0x8PzD1Dl:-Mwk3i774vA0x8PzD1Dm:b-mkdqxr) ([raw file](https://github.com/sepalani/mh3sp/blob/653e6a061839fd36f7cd342fd05699eb0fe8bac1/mh/database.py#L89)):*
> ```Python
>         self.leader = None
>         self.players.clear()
>         self.questId = 0
> ```

`self.quest_id`
___
*[mh/pat_item.py, line 433 at r6](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk6Ou71etFbPQZktyD:-Mwk6Ou71etFbPQZktyE:b-b6tsqh) ([raw file](https://github.com/sepalani/mh3sp/blob/a230bf2fe6c918147701ad88382aa503d5f3e24d/mh/pat_item.py#L433)):*
> ```Python
>                     key = field_id
>                     break
>             else:
> ```

Nice use of the `for..else` loop

**Review by InusualZ — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sepalani/mh3sp/35)* status: all files reviewed, 6 unresolved discussions (waiting on @sepalani)

___
*[-- commits, line 38 at r9](https://reviewable.io/reviews/sepalani/mh3sp/35#-MwkAcyu3yBHeY9nGvhE):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

`whether`
</blockquote></details>

Done.
___
*[fmp_server.py, line 752 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7hdT9Nq6W_2mmrJ2:-Mwq1EIq3ZfT7xJOG0ew:b-896fix) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L752)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

`because` (...) `the client ignores it`
</blockquote></details>

Done.
___
*[fmp_server.py, line 767 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7ttT5utvUxfinWIs:-Mwq1Em8Btm_lcmTDmeC:b-896fix) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L767)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[fmp_server.py, line 736 at r8](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk8jZo4U39NGqzKjAW:-Mwpn7T43ruTrK0UqaJC:b2uymul) ([raw file](https://github.com/sepalani/mh3sp/blob/8e5212f499533c0ae8c7319a588265246a822eaa/fmp_server.py#L736)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

Can't this code-logic stay in the `leave_circle` method? Won't something like this work in the `leave_circle` method?
```python
if circle.leader == self:
    circle.reset()
```
</blockquote></details>

Initially I had it like that, but now I can't seems to remember the reason to extract it from the function. I reverted the change
___
*[mh/database.py, line 89 at r1](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk3i774vA0x8PzD1Dl:-Mwq1F6O67H7vuE2hcVe:b-896fix) ([raw file](https://github.com/sepalani/mh3sp/blob/653e6a061839fd36f7cd342fd05699eb0fe8bac1/mh/database.py#L89)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

`self.quest_id`
</blockquote></details>

Done.
___
*[mh/pat_item.py, line 433 at r6](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk6Ou71etFbPQZktyD:-Mwq1Ftv8cWv8shTyaHE:b-xuyuoo) ([raw file](https://github.com/sepalani/mh3sp/blob/a230bf2fe6c918147701ad88382aa503d5f3e24d/mh/pat_item.py#L433)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

Nice use of the `for..else` loop
</blockquote></details>

I'm quite proud of it too XD

**Comment by InusualZ** [comment]
Give it another review because I force pushed 3 times and I'm always worried that I messed something up.

**Review by sepalani — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r17, 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sepalani/mh3sp/35)* status: all files reviewed, 2 unresolved discussions (waiting on @InusualZ)

___
*[fmp_server.py, line 752 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7hdT9Nq6W_2mmrJ2:-MwqdE4u79gDe-gllcmB:b6rs6k0) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L752)):*
<details><summary><i>Previously, InusualZ (Wesley Moret) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think there is a `s` missing at ignore**s**
___
*[fmp_server.py, line 767 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7ttT5utvUxfinWIs:-MwqdQc46d5FhNqSBiyx:b-89a4l7) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L767)):*
<details><summary><i>Previously, InusualZ (Wesley Moret) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ditto

**Review by InusualZ — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sepalani/mh3sp/35)* status: all files reviewed, 2 unresolved discussions (waiting on @sepalani)

___
*[fmp_server.py, line 752 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7hdT9Nq6W_2mmrJ2:-MwrAbyG4Np7ujr3Jijj:b-896fix) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L752)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

I think there is a `s` missing at ignore**s**
</blockquote></details>

Done.
___
*[fmp_server.py, line 767 at r7](https://reviewable.io/reviews/sepalani/mh3sp/35#-Mwk7ttT5utvUxfinWIs:-MwrAcF8AiL7z8DfFoOV:b-896fix) ([raw file](https://github.com/sepalani/mh3sp/blob/16c5d8d9e550f9d516d9a9c80d26c60b9c138f8e/fmp_server.py#L767)):*
<details><summary><i>Previously, sepalani wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.

**Comment by sepalani** [comment]
With the current PR state, I can't join a quest as it seems the current population is always `1/1` even when the team size isn't 1. Is that a regression?

Regarding the quest departure, it's seem to be working correctly even with multiple quests on the board.

**Comment by InusualZ** [comment]
Fixed :)

**Review by sepalani — APPROVED** [review]
> Reviewed 1 of 3 files at r26, 3 of 3 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sepalani/mh3sp/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @InusualZ)

**Pull request merged**
